controlAereo/models/usuario.py
from controlAereo import db

class Usuario(db.Model):
    __tablename__ = 'usuario'
    idUsuario = db.Column(db.Integer, primary_key=True)
    nombreCompleto = db.Column(db.String(50))
    email = db.Column(db.String(50))
    celular = db.Column(db.Text)
    password = db.Column(db.Text)
    idTipoUsuario = db.Column(db.Integer)
    estadoUsuario = db.Column(db.Integer)
    
    def __init__(self, nombreCompleto, email, celular, password, idTipoUsuario, estadoUsuario) -> None:
        self.nombreCompleto = nombreCompleto
        self.email = email
        self.celular = celular
        self.password = password
        self.idTipoUsuario = idTipoUsuario
        self.estadoUsuario = estadoUsuario

    def __repr__(self) -> str:
        dataUsuarios = {
            'idUsuario': self.idUsuario,
            'nombreCompleto': self.nombreCompleto,
            'email': self.email,
            'celular': self.celular,
            'idTipoUsuario': self.idTipoUsuario,
            'estadoUsuario': self.estadoUsuario
        }
        return f'{dataUsuarios}'

controlAereo/views/usuario.py
from flask import render_template, Blueprint, flash, g, redirect, request, url_for
from controlAereo.models.vuelo import Vuelo
from controlAereo.models.usuario import Usuario
from controlAereo.models.reservaVuelo import Reserva
from controlAereo.views.auth import login_required
from controlAereo import db

usuario = Blueprint('usuario', __name__)

def getUsuario(id):
    usuario = Usuario.query.get_or_404(id)
    return usuario

#Listar todos los usuarios
@usuario.route("/control/usuarios")
@login_required
def listarUsuarios():
    usuarios = Usuario.query.all()
    db.session.commit()
    data = {
        'usuarios': usuarios
    }
    return render_template('controlAereo/usuarios.html', **data)

#Listar todos los pilotos
@usuario.route("/control/usuarios")
@login_required
def listarPilotos():
    pilotos = Usuario.query.filter_by(idTipoUsuario = 2).all()
    db.session.commit()
    return pilotos

#Crear usuarios (reutilizado de la creacion de AUTH)
@usuario.route('/control/crearUsuario')
@login_required
def crearUsuario():
     return redirect(url_for('auth.register'))

@usuario.route('/editarusuario/<int:id>', methods=['GET', 'POST'])
@login_required
def editarUsuario(id):
    usuario = getUsuario(id)

    if request.method == 'POST':

        usuario.nombreCompleto = request.form['nombreCompleto']
        usuario.email = request.form['email']
        usuario.celular = request.form['celular']
        usuario.idTipoUsuario = request.form['idTipoUsuario']
        usuario.estadoUsuario = request.form['estadoUsuario']

        dataRespuesta = {
            'usuario': None,
            'respuesta': True,
        }

        db.session.add(usuario)
        db.session.commit()
        dataRespuesta['usuario'] = usuario

        flash(dataRespuesta)

    return render_template('controlAereo/editarUsuario.html', usuario=usuario)

controlAereo/templates/controlAereo/creaReserva.html
{% if session['idTipoUsuario'] == 1 or session['idTipoUsuario'] == 3 %}
{% extends "base_inicio.html" %}
{% block title %}Crear Reserva{% endblock  %}
{% block css %}
{% endblock %}
{% block contentInicio %}
<div class="col-lg-6">
  <div class="">
    <div class="card mt-5">
      <div class="card-header dark">
          <h3 class="card-title">Crear Reserva&nbsp&nbsp&nbsp<i class="fas fa-plane"></i></h3>
      </div>
      <div class="card-body register-card-body">
        <form action="" method="POST">
        <div class="">
          {% if session['estado'] and session['idTipoUsuario'] == 1%}
          <div class="input-group mb-3">
            <select class="custom-select" id="estado" name="idUsuario" required>
                <option value="" selected disabled>Seleccione Pasajero</option>
                {% for usuario in usuarios %}
                    {% if usuario['idTipoUsuario'] != 2%}
                    <option value="{{usuario['idUsuario']}}">{{usuario['nombreCompleto']}}</option>
                    {% endif %}
                {% endfor %}
            </select>
            <div class="input-group-append">
              <label class="input-group-text" for="estado"><i class="fas fa-user-tag"></i></label>
            </div>
          </div>
          {% else %}
          <input type="hidden" value="{{session['idUsuario']}}" name="idUsuario" class="form-control" placeholder="">
          {% endif %}
          <div class="input-group mb-3">
            <select class="custom-select" id="estado" name="idVuelo" required>
                <option value="" selected disabled>Seleccione Destino</option>
                {% for vuelo in vuelos %}
                    <option value="{{vuelo['idVuelo']}}">Vuelo N°{{vuelo['idVuelo']}} Con Destino a {{vuelo['destino']}}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
              <label class="input-group-text" for="idVuelo"><i class="fas fa-plane-arrival"></i></label>
            </div>
          </div>
        </div>
        <div class="row mb-3">
        <div class="col-6">
            <button type="submit" class="btn btn-mision-pri btn-block">Crear Reserva</button>
        </div>
        <div class="col-6">
            <a href="/" class="btn btn-block btn-mision-sec">
            <i class=""></i> Cancelar
            </a>
        </div>
        </div>
        <div class="row">
        </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
{% endblock%}
{% else %}
  No se puede mostrar
{% endif %}

controlAereo/templates/controlAereo/crearVuelo.html
{% if session['idTipoUsuario'] == 1 %}
{% extends "base_inicio.html" %}
{% block title %}Crear Vuelo{% endblock  %}
{% block css %}
<link rel="stylesheet" href="../static/datepicker/css/bootstrap-datepicker.standalone.css">
<link rel="stylesheet" href="../static/datepicker/css/bootstrap-datetimepicker.min.css">
{% endblock %}
{% block contentInicio %}
<div class="col-lg-4">
  <div class="">
    <div class="card mt-4">
      <div class="card-header dark">
          <h3 class="card-title">Crear Nuevo Vuelo&nbsp&nbsp&nbsp<i class="fas fa-plane"></i></h3>
      </div>
      <div class="card-body register-card-body">
        <form action="" method="POST">
          <div class="input-group mb-3">
            <input type="text" name="origen" class="form-control" placeholder="Origen" required>
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-plane-departure"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <input type="text" name="destino" class="form-control" placeholder="Destino" required>
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fas fa-plane-arrival"></span>
              </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <div class="input-group date" id="fechaVuelo" data-target-input="nearest">
                <input type="text" name="fecha" id="fechaVuelo" class="form-control datetimepicker-input" data-target="#fechaVuelo" placeholder="Fecha">
                <div class="input-group-append" data-target="#fechaVuelo" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <div class="input-group date" id="" data-target-input="nearest">
                <input class="form-control" name="hora" type="text" id="datetimepicker" placeholder="Hora">
                <div class="input-group-append" data-target="#datetimepicker" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="far fa-clock"></i></div>
                </div>
            </div>
          </div>
          <div class="input-group mb-3">
            <select class="custom-select" id="idPiloto" name="idPiloto" required>
                <option value="" selected disabled>Seleccione Piloto</option>
                {% for piloto in pilotos %}
                    <option value="{{piloto['idUsuario']}}">{{piloto['nombreCompleto']}}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
              <label class="input-group-text" for="idPiloto"><i class="fas fa-user-tie"></i></label>
            </div>
          </div>
          <div class="input-group mb-3">
            <select class="custom-select" id="idAvion" name="idAvion" required>
                <option value="" selected disabled>Seleccione Avion</option>
                {% for avion in aviones %}
                    <option value="{{avion['idAvion']}}">{{avion['referencia']}}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
              <label class="input-group-text" for="idAvion"><i class="fas fa-plane"></i></label>
            </div>
          </div>
          <div class="input-group mb-3">
            <select class="custom-select" id="estado" name="estado">
              <option value="" selected disabled>Seleccione Estado</option>
              <option value="Programado">Programado</option>
              <option value="En Tiempo">En Tiempo</option>
              <option value="Retrasado">Retrasado</option>
              <option value="Aterrizo">Aterrizo</option>
              <option value="Despego">Despego</option>
            </select>
            <div class="input-group-append">
              <label class="input-group-text" for="estado"><i class="fas fa-plane"></i></label>
            </div>
          </div>
          <div class="row mb-3">
            <div class="col-6">
              <button type="submit" class="btn btn-mision-pri btn-block">Crear Vuelo</button>
            </div>
            <div class="col-6">
              <a href="/" class="btn btn-block btn-mision-sec">
                <i class=""></i> Cancelar
              </a>
            </div>
          </div>
          <div class="row">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
<script src="../static/datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="../static/datepicker/locales/bootstrap-datepicker.es.min.js"></script>
<script src="../static/datepicker/js/moment.min.js"></script>
<script src="../static/datepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="../static/js/js.js"></script>
{% endblock%}
{% else %}
<h4>No Tiene Permisos para Ingresar a Esta Pagina</h4>
{% endif %}

controlAereo/templates/controlAereo/editarUsuario.html
{% if session['estado'] %}
{% extends "base_inicio.html" %}
{% block title %}Editar Usuario{% endblock %}
{% block contentInicio %}
<div class="col-lg-6 mt-4">
  <div class="card">
    <div class="card-header">
        <h3 class="card-title">Editar Usuario&nbsp&nbsp&nbsp<i class="fas fa-user-plus"></i></h3>
    </div>
    <div class="card-body register-card-body">
      <form action="" method="POST">
        <div class="input-group mb-3">
          <input type="text" name="nombreCompleto" class="form-control" placeholder="Nombre Completo" value="{{usuario.nombreCompleto}}"required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Email" value="{{usuario.email}}" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="phone" name="celular" class="form-control" placeholder="Numero Celular" value="{{usuario.celular}}" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <i class="fas fa-mobile-alt"></i>
            </div>
          </div>
        </div>
        {% if session['idTipoUsuario'] == 1 %}
        <div class="input-group mb-3">
          <select class="custom-select" id="idTipoUsuario" name="idTipoUsuario" required>
            <option value="{{usuario.idTipoUsuario}}" selected>
            {% if usuario.idTipoUsuario == 1 %}
            Administrador
            {% elif usuario.idTipoUsuario == 2 %}
            Piloto
            {% elif usuario.idTipoUsuario == 3 %}
            Usuario Final
            {% endif %}
            </option>
            {% if usuario.idTipoUsuario != 1 %}
            <option value="1">Administrador</option>
            {% endif %}
            {% if usuario.idTipoUsuario != 2 %}
            <option value="2">Piloto</option>
            {% endif %}
            {% if usuario.idTipoUsuario != 3 %}
            <option value="3">Usuario Final</option>
            {% endif %}
          </select>
          <div class="input-group-append">
            <label class="input-group-text" for="idTipoUsuario"><i class="fas fa-user"></i></label>
          </div>
        </div>
        <div class="input-group mb-3">
          <select class="custom-select" id="estadoUsuario" name="estadoUsuario" required>
            <option value="{{usuario.estadoUsuario}}" selected>
            {% if usuario.estadoUsuario == 1 %}
            Activo
            {% elif usuario.estadoUsuario == 0 %}
            Inactivo
            {% endif %}
            </option>
            {% if usuario.estadoUsuario != 1 %}
            <option value="1">Activo</option>
            {% endif %}
            {% if usuario.estadoUsuario != 0 %}
            <option value="0">Inactivo</option>
            {% endif %}
          </select>
          <div class="input-group-append">
            <label class="input-group-text" for="idTipoUsuario"><i class="fas fa-user"></i></label>
          </div>
        </div>
        {% else %}
        <input type="hidden" value="{{usuario.idTipoUsuario}}" name="idTipoUsuario" class="form-control" placeholder="">
        <input type="hidden" value="{{usuario.estadoUsuario}}" name="estadoUsuario" class="form-control" placeholder="">
        {% endif %}
        <!-- PENDIENTE IMPLEMENTAR CAMBIO DE CONTRASEÑA !-->
        <!--
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Password" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="Confirma Password" required>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        !-->
        <div class="row mb-3">
          <div class="col-6">
            <button type="submit" class="btn btn-mision-pri btn-block">Actualizar</button>
          </div>
          <div class="col-6">
            {% if session['idUsuario'] == 1 %}
            <a href="/control/usuarios" class="btn btn-block btn-mision-sec">
              <i class=""></i> Cancelar
            </a>
            {% else %}
            <a href="/" class="btn btn-block btn-mision-sec">
              <i class=""></i> Cancelar
            </a>
            {% endif %}
          </div>
        </div>
        <div class="row">
        {% for message in get_flashed_messages() %}
        {% if message.respuesta %}
          <div class="col-12 alert alert-success">
            El Usuario <strong>{{ message.usuario['nombreCompleto'] }}</strong> fue actualizado correctamente
          </div>
        {% else %}
          <div class="col-12 alert alert-danger">
            El Usuario <strong>{{ message.usuario['nombreCompleto'] }}</strong> ya existe
          </div>
        {% endif %}
        {% endfor %}
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}
{% else %}
<h4>No Tiene Permisos para Ingresar a Esta Pagina</h4>
{% endif %}

controlAereo/templates/controlAereo/index.html
{% extends "base_inicio.html" %}
{% block title %}Inicio{% endblock  %}
{% block contentInicio %}
<div class="col-lg-6 mt-4">
    <div class="card">
        <div class="card-header dark">
            <h3 class="card-title">Informacion de Vuelos&nbsp&nbsp&nbsp<i class="fas fa-plane"></i></h3>
        </div>
        <div class="card-body">
        <table class="table table-bordered">
            <thead class="thead-mision">
            <tr>
                <th style="width: 20%">Vuelo N°</th>
                <th style="width: 30%">Origen&nbsp&nbsp&nbsp<span class="fas fa-plane-departure"></span></th>
                <th style="width: 30%">Destino&nbsp&nbsp&nbsp<span class="fas fa-plane-arrival"></span></th>
                <th style="width: 20%">Estado&nbsp&nbsp&nbsp<i class="fas fa-plane"></i></th>
            </tr>
            </thead>
            <tbody>
            {% for vuelo in vuelos %}
            <tr>
                <td>{{ vuelo.idVuelo }}</td>
                <td>{{ vuelo.origen }}</td>
                <td>{{ vuelo.destino }}</td>
                {% if vuelo.estado == "Programado" %}
                    <td><h5><small class="badge badge-warning"><i class="far fa-clock"></i>&nbsp&nbsp{{ vuelo.estado }}</small></h5></td>
                {% elif vuelo.estado == "En Tiempo" %}
                    <td><h5><small class="badge badge-success"><i class="far fa-clock"></i>&nbsp&nbsp{{ vuelo.estado }}</small></h5></td>
                {% elif vuelo.estado == "Retrasado" %}
                    <td><h5><small class="badge badge-danger"><i class="far fa-clock"></i>&nbsp&nbsp{{ vuelo.estado }}</small></h5></td>
                {% elif vuelo.estado == "Aterrizo" %}
                    <td><h5><small class="badge badge-dark"><i class="fas fa-plane-arrival"></i>&nbsp&nbsp{{ vuelo.estado }}</small></h5></td>
                {% elif vuelo.estado == "Despego" %}
                    <td><h5><small class="badge badge-info"><i class="fas fa-plane-departure"></i>&nbsp&nbsp{{ vuelo.estado }}</small></h5></td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% if session['estado'] and session['idTipoUsuario'] == 1 %}
<div class="col-lg-6 mt-4">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Informacion de Pasajeros&nbsp&nbsp&nbsp<i class="fas fa-users"></i></h3>
        </div>
        <div class="card-body">
        <table class="table table-bordered">
            <thead class="thead-mision">
                <tr>
                    <th style="width: 20%">Vuelo N°</th>
                    <th style="width: 30%">Usuario&nbsp&nbsp&nbsp<i class="fas fa-user"></i></th>
                    <th style="width: 50%">Destino&nbsp&nbsp&nbsp<span class="fas fa-plane-arrival"></span></th>
                </tr>
            </thead>
            <tbody>
                {% for pasajero in pasajeros %}
                <tr>
                    <td>{{pasajero[2]['idVuelo']}}</td>
                    <td>{{pasajero[0]['nombreCompleto']}}</td>
                    <td>{{pasajero[2]['destino']}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

controlAereo/templates/controlAereo/infoReserva.html
{% if session['estado'] and session['idTipoUsuario'] != 2 %}
{% extends "base_inicio.html" %}
{% block title %}Mis Reservas{% endblock  %}
{% block css %}
{% endblock %}
{% block contentInicio %}
<div class="col-lg-12">
  <div class="">
    <div class="card mt-5">
        <div class="card-header dark">
            <h3 class="card-title">Mis Reservas&nbsp&nbsp&nbsp<i class="fas fa-plane"></i></h3>
        </div>
        <div class="card-body register-card-body">
            <table class="table table-bordered mt-3">
                <thead class="thead-mision">
                    <tr>
                        <th style="width: 10%">Reserva N°&nbsp&nbsp&nbsp</th>
                        <th style="width: 10%">Vuelo N°&nbsp&nbsp&nbsp</th>
                        <th style="width: 20%">Origen&nbsp&nbsp&nbsp</th>
                        <th style="width: 20%">Destino&nbsp&nbsp&nbsp</th>
                        <th style="width: 10%">Avion</th>
                        <th style="width: 15%">Piloto&nbsp&nbsp&nbsp</th>
                        <th style="width: 10%">Capacidad&nbsp&nbsp&nbsp</th>
                        <th style="width: 15%">Estado&nbsp&nbsp&nbsp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for info in infoReserva %}
                    <tr>
                        <td>{{infoReserva[loop.index-1][0]['idReserva']}}</td>
                        <td>{{infoReserva[loop.index-1][0]['idVuelo']}}</td>
                        <td>{{infoReserva[loop.index-1][1]['origen']}}</td>
                        <td>{{infoReserva[loop.index-1][1]['destino']}}</td>
                        <td>{{infoReserva[loop.index-1][2]['referencia']}}</td>
                        <td>{{infoReserva[loop.index-1][3]['nombreCompleto']}}</td>
                        <td>{{infoReserva[loop.index-1][2]['capacidad']}} Pasajeros</td>
                        {% if infoReserva[loop.index-1][1]['estado'] == "Programado" %}
                            <td><h5><small class="badge badge-warning"><i class="far fa-clock"></i>&nbsp&nbsp{{ infoReserva[loop.index-1][1]['estado'] }}</small></h5></td>
                        {% elif infoReserva[loop.index-1][1]['estado'] == "En Tiempo" %}
                            <td><h5><small class="badge badge-success"><i class="far fa-clock"></i>&nbsp&nbsp{{ infoReserva[loop.index-1][1]['estado'] }}</small></h5></td>
                        {% elif infoReserva[loop.index-1][1]['estado'] == "Retrasado" %}
                            <td><h5><small class="badge badge-danger"><i class="far fa-clock"></i>&nbsp&nbsp{{ infoReserva[loop.index-1][1]['estado'] }}</small></h5></td>
                        {% elif infoReserva[loop.index-1][1]['estado'] == "Aterrizo" %}
                            <td><h5><small class="badge badge-dark"><i class="fas fa-plane-arrival"></i>&nbsp&nbsp{{ infoReserva[loop.index-1][1]['estado'] }}</small></h5></td>
                        {% elif infoReserva[loop.index-1][1]['estado'] == "Despego" %}
                            <td><h5><small class="badge badge-info"><i class="fas fa-plane-departure"></i>&nbsp&nbsp{{ infoReserva[loop.index-1][1]['estado'] }}</small></h5></td>
                        {% endif %}
                        
                          
                    </tr>
                   
                    {% endfor %}
                </tbody>
            </table> 
        </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
{% endblock%}
{% else %}
<h4>No Tiene Permisos para Ingresar a Esta Pagina</h4>
{% endif %}

controlAereo/templates/controlAereo/usuarios.html
{% if session['idTipoUsuario'] == 1 %}
{% extends "base_inicio.html" %}
{% block title %}Gestion Usuarios{% endblock  %}
{% block css %}
{% endblock %}
{% block contentInicio %}
<div class="col-lg-10">
  <div class="">
    <div class="card mt-5">
        <div class="card-header dark">
            <h3 class="card-title">Gestion de Usuarios&nbsp&nbsp&nbsp<i class="fas fa-users"></i></h3>
        </div>
        <div class="card-body register-card-body">
            <div class="btn-group btn-group-sm">
                <a href="{{url_for('usuario.crearUsuario')}}" class="btn btn-success"><i class="fas fa-user-plus">&nbsp&nbsp</i>Crear Usuario</a>
            </div>
            <table class="table table-bordered mt-3">
                <thead class="thead-mision">
                    <tr>
                        <th style="width: 20%">Nombre Completo&nbsp&nbsp&nbsp</th>
                        <th style="width: 20%">Email</th>
                        <th style="width: 20%">Tipo de Usuario&nbsp&nbsp&nbsp</th>
                        <th style="width: 10%">Estado&nbsp&nbsp&nbsp</th>
                        <th style="width: 10%">Gestion&nbsp&nbsp&nbsp</th>
                    </tr>
                </thead>
                <tbody>
                    {% for usuario in usuarios %}
                    <tr>
                        <td>{{usuario['nombreCompleto']}}</td>
                        <td>{{usuario['email']}}</td>
                        {% if usuario['idTipoUsuario'] == 1 %}
                            <td>Administrador</td>
                        {% elif usuario['idTipoUsuario'] == 2 %}
                            <td>Piloto</td>
                        {% elif usuario['idTipoUsuario'] == 3 %}
                            <td>Usuario Final</td>
                        {% endif %}
                        <td>
                        {% if usuario['estadoUsuario'] == 1 %}
                            <div class="btn-group btn-group-sm">
                                <a href="" class="btn btn-success btnInactivo"><i class="fas fa-check-circle">&nbsp</i>Activo</a>
                            </div>
                        {% else %}
                            <div class="btn-group btn-group-sm">
                                <a href="" class="btn btn-danger btnInactivo"><i class="fas fa-times-circle">&nbsp</i>Inactivo</a>
                            </div>
                        {% endif %}
                            
                        </td>
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="{{ url_for('usuario.editarUsuario', id=usuario['idUsuario']) }}" class="btn btn-mision-pri"><i class="fas fa-edit">&nbsp</i>Editar</a>
                            </div>
                        </td>  
                    </tr>
                    {% endfor %}
                </tbody>
            </table> 
        </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
{% endblock%}
{% else %}
<h4>No Tiene Permisos para Ingresar a Esta Pagina</h4>
{% endif %}