controlAereo/views/auth.py
import functools
from flask import render_template, Blueprint, flash, g, redirect, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash
import controlAereo
from controlAereo.models.usuario import Usuario
from controlAereo import db

auth = Blueprint('auth', __name__, url_prefix='/auth')

#Registrar Usuario
@auth.route('/register', methods=['GET','POST'])
def register():
    if request.method == 'POST':
        nombreCompleto = request.form['nombreCompleto']
        email = request.form['email']
        celular = request.form['celular']
        password = request.form['password']
        idTipoUsuario = request.form['idTipoUsuario']
        estadoUsuario = request.form['estadoUsuario']

        usuario = Usuario(nombreCompleto.title(), email, celular, generate_password_hash(password), idTipoUsuario, estadoUsuario)
        usuarioExiste = Usuario.query.filter_by(email = email).first()

        dataRespuesta = {
            'usuario': None,
            'respuesta': False,
        }

        if usuarioExiste:
            dataRespuesta['usuario'] = usuarioExiste
        else:
            db.session.add(usuario)
            db.session.commit()
            dataRespuesta['usuario'] = usuario
            dataRespuesta['respuesta'] = True

        flash(dataRespuesta)

    return render_template('auth/register.html')

#Iniciar Sesión
@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        usuario = Usuario.query.filter_by(email = email).first()

        if usuario and check_password_hash(usuario.password, password):
            if usuario.estadoUsuario == 1:
                session.clear()
                session['idUsuario'] = usuario.idUsuario
                session['nombreUsuario'] = usuario.nombreCompleto
                session['idTipoUsuario'] = usuario.idTipoUsuario
                if usuario.idTipoUsuario == 1:
                    session['tipoUsuario'] = 'Administrador'
                elif usuario.idTipoUsuario == 2:
                    session['tipoUsuario'] = 'Piloto'
                elif usuario.idTipoUsuario == 3:
                    session['tipoUsuario'] = 'Usuario Final'
                session['estadoUsuario'] = usuario.estadoUsuario
                session['estado'] = True
                return redirect(url_for('vuelo.index'))
            else:
                session.clear()
                session['estado'] = False
        else:
            session.clear()
            session['estado'] = False
            
        flash(session)

    return render_template('auth/login.html')

#Comprueba si el usuario tiene sesion activa
@auth.before_app_request
def load_logged_in_user():
    idUsuario = session.get('idUsuario')

    if idUsuario is None:
        g.usuario = None
    else:   
        g.usuario = Usuario.query.get_or_404(idUsuario)

#Cierra sesion
@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('vuelo.index'))

#valida login requerido
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.usuario is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

controlAereo/views/usuario.py
from flask import render_template, Blueprint, flash, g, redirect, request, url_for
from controlAereo.models.vuelo import Vuelo
from controlAereo.models.usuario import Usuario
from controlAereo.models.reservaVuelo import Reserva
from controlAereo.views.auth import login_required
from controlAereo import db

usuario = Blueprint('usuario', __name__)

def getUsuario(id):
    usuario = Usuario.query.get_or_404(id)
    return usuario

#Listar todos los usuarios
@usuario.route("/control/usuarios")
@login_required
def listarUsuarios():
    usuarios = Usuario.query.all()
    db.session.commit()
    data = {
        'usuarios': usuarios
    }
    return render_template('controlAereo/usuarios.html', **data)

#Listar todos los pilotos
@usuario.route("/control/usuarios")
@login_required
def listarPilotos():
    pilotos = Usuario.query.filter_by(idTipoUsuario = 2).all()
    db.session.commit()
    return pilotos

#Crear usuarios (reutilizado de la creacion de AUTH)
@usuario.route('/control/crearUsuario')
@login_required
def crearUsuario():
     return redirect(url_for('auth.register'))

@usuario.route('/editarusuario/<int:id>', methods=['GET', 'POST'])
@login_required
def editarUsuario(id):
    usuario = getUsuario(id)

    if request.method == 'POST':

        usuario.nombreCompleto = request.form['nombreCompleto']
        usuario.email = request.form['email']
        usuario.celular = request.form['celular']
        usuario.idTipoUsuario = request.form['idTipoUsuario']
        usuario.estadoUsuario = request.form['estadoUsuario']

        dataRespuesta = {
            'usuario': None,
            'respuesta': True,
        }

        db.session.add(usuario)
        db.session.commit()
        dataRespuesta['usuario'] = usuario

        flash(dataRespuesta)

    return render_template('controlAereo/editarUsuario.html', usuario=usuario)

controlAereo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Controlador Aereo | {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link rel="stylesheet" href="../static/fontawesome-free/css/all.min.css">
  <link rel="stylesheet" href="../static/icheck-bootstrap/icheck-bootstrap.min.css">
  <link rel="stylesheet" href="../static/dist/css/adminlte.min.css">
  <link rel="stylesheet" href="../static/css/misestilos.css">
  {% block css %}{% endblock %}
</head>
<body class="hold-transition">
{% block content %}{% endblock %}
<script src="../static/jquery/jquery.min.js"></script>
<script src="../static/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="../static/dist/js/adminlte.min.js"></script>
{% block scripts %}{% endblock%}
</body>
</html>

controlAereo/templates/base_inicio.html
{% extends "base.html" %}
{% block content %}
<div class="wrapper sidebar-mini">
  <nav class="main-header navbar navbar-expand navbar-white navbar-light mb-0">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Inicio</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contacto</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Buscar" aria-label="Buscar">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>
    </ul>
  </nav>
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="/" class="brand-link">
      <img src="../../static/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Misión Air | Control</span>
    </a>
    <div class="sidebar">
      {% if session['nombreUsuario'] %}
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="../../static/dist/img/user8-128x128.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="" class="d-block" style="pointer-events: none; cursor: default">{{session['nombreUsuario']}}</a>
          <a href="" class="d-block" style="pointer-events: none; cursor: default">{{session['tipoUsuario']}}</a>
          <a href="{{ url_for('usuario.editarUsuario', id=session['idUsuario']) }}" class="d-block">Editar Informacion</a>
        </div>
      </div>
      {% endif %}
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          {% if session['estado'] %}
          <li class="nav-item">
            <a href="/" class="nav-link">
              <i class="fas fa-home">&nbsp</i>
              <p>
                Inicio
              </p>
            </a>
          </li>
          {% endif %}
          {% if session['estado'] and session['idTipoUsuario'] == 1 %}
           <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-user-cog">&nbsp</i>
              <p>
                Administrar Sistema
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              <li class="nav-item">
                <a href="/control/usuarios" class="nav-link">
                  <i class="fas fa-chevron-right">&nbsp</i>
                  <p>Gestion de Usuarios</p>
                </a>
              </li>
            </ul>
          </li>
          {% endif %}
          {% if session['estado'] %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas fa-plane">&nbsp</i>
              <p>
                Vuelos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              {% if session['idTipoUsuario'] == 1%}
              <li class="nav-item">
                <a href="/control/creavuelo" class="nav-link">
                  <i class="fas fa-chevron-right">&nbsp</i>
                  <p>Crear Vuelo</p>
                </a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a href="/control/infovuelos" class="nav-link">
                  <i class="fas fa-chevron-right">&nbsp</i>
                  <p>Informacion Vuelos</p>
                </a>
              </li>
            </ul>
          </li>
          {% if session['idTipoUsuario'] != 2%}
          <li class="nav-item">
            <a href="#" class="nav-link">
            <i class="far fa-calendar-alt">&nbsp</i>
              <p>
                Reservas
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview" style="display: none;">
              <li class="nav-item">
                <a href="/control/creareserva" class="nav-link">
                  <i class="fas fa-chevron-right">&nbsp</i>
                  <p>Crear Reserva</p>
                </a>
              </li>
              {% if session['idTipoUsuario'] != 2%}
              <li class="nav-item">
                <a href="/inforeserva/{{session['idUsuario']}}" class="nav-link">
                  <i class="fas fa-chevron-right">&nbsp</i>
                  <p>Mis reservas</p>
                </a>
              </li>
              {% endif %}
            </ul>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{{ url_for('auth.logout')}}" class="nav-link">
              <i class="fas fa-sign-out-alt">&nbsp</i>
              <p>
                Cerrar Sesión
              </p>
            </a>
          </li>
          {% endif %}
          {% if not session['estado']%}
          <li class="nav-item">
            <a href="/auth/login" class="nav-link">
              <i class="fas fa-sign-in-alt">&nbsp</i>
              <p>
                Ingresar
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/auth/register" class="nav-link">
            <i class="fas fa-user-plus"></i>
              <p>
                Registrarse
              </p>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </aside>
  <div class="content-wrapper">
    <div class="content">
      <div class="container-fluid">
        <div class="row justify-content-lg-center">
            {% block contentInicio %}
            {% endblock %}
        </div>
      </div>
    </div>
  </div>
  <aside class="control-sidebar control-sidebar-dark">
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>
  <footer class="main-footer">
    <strong>Copyright &copy; <a href="">Juan Pablo Espinosa Grupo 55 - 2  2022</a>.</strong> Todos los derechos reservados.
  </footer>
</div>
{% endblock %}